"use client";

import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { CommunityComment, CommunityPost, CommunityProfile, CommunitySession, banCommunityMember, createCommunityAccount, createCommunityComment, createCommunityPost, deleteCommunityComment, deleteCommunityPost, getCommunityProfile, listCommunityComments, listCommunityMembers, listCommunityPosts, saveCommunityProfile, signInCommunity, updateCommunityPost } from "@/src/lib/firebase/community";
import { saveCatalogOverride } from "@/src/lib/firebase/catalog";
import { compressImage } from "@/src/lib/image/quality";
import { baseSpecies } from "@/src/data/baseSpecies";
import { UserProfile } from "@/src/types";

const sessionKey = "mudflat-log:community-session";
const adminEmail = "nowimminjun@gmail.com";
const avatars = ["🦀", "🐟", "🐚", "🦆", "🦐"];
const readSession = (): CommunitySession | null => { try { return JSON.parse(localStorage.getItem(sessionKey) ?? "null"); } catch { return null; } };

export default function Community({ localProfile }: { localProfile: UserProfile }) {
  const [session, setSession] = useState<CommunitySession | null>(null), [profile, setProfile] = useState<CommunityProfile | null>(null), [posts, setPosts] = useState<CommunityPost[]>([]), [selected, setSelected] = useState<CommunityPost | null>(null), [comments, setComments] = useState<CommunityComment[]>([]), [email, setEmail] = useState(localProfile.email ?? ""), [password, setPassword] = useState(""), [nickname, setNickname] = useState(localProfile.nickname), [avatar, setAvatar] = useState("🦀"), [intro, setIntro] = useState(""), [title, setTitle] = useState(""), [body, setBody] = useState(""), [photo, setPhoto] = useState(""), [comment, setComment] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false), [editing, setEditing] = useState(false);
  const refreshPosts = async (active = session) => { if (active) setPosts(await listCommunityPosts(active)); };
  useEffect(() => { const existing = readSession(); if (existing) setSession(existing); }, []);
  useEffect(() => { if (!session) return; refreshPosts(); getCommunityProfile(session, session.uid).then(saved => { if (saved) { setProfile(saved); setNickname(saved.nickname); setAvatar(saved.avatar); setIntro(saved.intro); } }); }, [session]);
  useEffect(() => { if (selected && session) listCommunityComments(session, selected.id).then(setComments); }, [selected, session]);
  const connect = async (create: boolean) => { if (!email || password.length < 6) return setError("이메일과 6자 이상 비밀번호를 입력해 주세요."); setBusy(true); try { const next = create ? await createCommunityAccount(email, password) : await signInCommunity(email, password); localStorage.setItem(sessionKey, JSON.stringify(next)); setSession(next); } catch { setError("이메일 또는 비밀번호를 확인해 주세요."); } finally { setBusy(false); } };
  const saveProfile = async () => { if (!session || !nickname.trim()) return; const next = { uid: session.uid, email: session.email, nickname: nickname.trim(), avatar, intro: intro.trim() }; await saveCommunityProfile(session, next); setProfile(next); };
  const choosePhoto = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const compressed = await compressImage(file); if (compressed.length > 650000) return setError("사진이 너무 큽니다. 더 작은 사진을 선택해 주세요."); setPhoto(compressed); event.target.value = ""; };
  const publish = async (event: FormEvent) => { event.preventDefault(); if (!session || !profile || !title.trim() || !body.trim()) return; setBusy(true); try { await createCommunityPost(session, { authorId: session.uid, authorName: profile.nickname, authorAvatar: profile.avatar, title: title.trim(), body: body.trim(), photo: photo || undefined, createdAt: new Date().toISOString() }); setTitle(""); setBody(""); setPhoto(""); await refreshPosts(); } catch { setError("게시글을 등록하지 못했습니다."); } finally { setBusy(false); } };
  const addComment = async (event: FormEvent) => { event.preventDefault(); if (!session || !profile || !selected || !comment.trim()) return; await createCommunityComment(session, selected.id, { authorId: session.uid, authorName: profile.nickname, authorAvatar: profile.avatar, body: comment.trim(), createdAt: new Date().toISOString() }); setComment(""); setComments(await listCommunityComments(session, selected.id)); };
  const saveEdit = async () => { if (!session || !selected) return; await updateCommunityPost(session, selected); setEditing(false); await refreshPosts(); };
  const removePost = async () => { if (!session || !selected || !confirm("이 게시글을 삭제할까요?")) return; await deleteCommunityPost(session, selected.id); setSelected(null); await refreshPosts(); };
  if (!session) return <section className="screen community"><p className="eyebrow">COMMUNITY</p><h1>갯벌 생물<br />함께 알아보기</h1><label>이메일<input type="email" value={email} onChange={e => setEmail(e.target.value)} /></label><label>비밀번호<input type="password" value={password} onChange={e => setPassword(e.target.value)} /></label>{error && <p className="error">{error}</p>}<button className="primary" disabled={busy} onClick={() => connect(false)}>커뮤니티 로그인</button><button className="secondary" disabled={busy} onClick={() => connect(true)}>커뮤니티 계정 만들기</button></section>;
  if (session.email === adminEmail) return <><AdminDashboard session={session} posts={posts} onRefresh={refreshPosts} /><AdminModeration session={session} /></>;
  return <section className="screen community"><p className="eyebrow">COMMUNITY</p><h1>갯벌 생물<br />함께 알아보기</h1>{error && <p className="error">{error}</p>}<section className="card community-profile"><div className="profile-head"><span>{avatar}</span><div><b>{profile?.nickname || "프로필 설정 필요"}</b><small>{profile?.intro || "나의 갯벌 탐방 정보를 소개해 보세요."}</small></div></div><label>닉네임<input value={nickname} onChange={e => setNickname(e.target.value)} /></label><label>소개<input value={intro} onChange={e => setIntro(e.target.value)} /></label><div className="avatar-picker">{avatars.map(item => <button type="button" className={avatar === item ? "active" : ""} onClick={() => setAvatar(item)} key={item}>{item}</button>)}</div><button className="secondary" onClick={saveProfile}>프로필 저장</button></section>{profile && <form className="card community-form" onSubmit={publish}><h2>미확인 생물 질문 올리기</h2><label>제목<input value={title} onChange={e => setTitle(e.target.value)} /></label><label>관찰 내용<textarea value={body} onChange={e => setBody(e.target.value)} /></label><label>사진 첨부<input type="file" accept="image/*" onChange={choosePhoto} /></label>{photo && <img className="community-full-image" src={photo} alt="첨부할 사진" />}<button className="primary" disabled={busy}>게시하기</button></form>}<div className="section-heading"><h2>커뮤니티 글</h2><button onClick={() => refreshPosts()}>새로고침</button></div><div className="cards">{posts.map(post => <button className="community-post" onClick={() => { setSelected(post); setEditing(false); }} key={post.id}><span>{post.authorAvatar} {post.authorName}</span><b>{post.title}</b>{post.photo && <img src={post.photo} alt="게시글 사진" />}<small>{post.body}</small></button>)}</div>{selected && <PostModal post={selected} setPost={setSelected} comments={comments} comment={comment} setComment={setComment} onComment={addComment} onEdit={saveEdit} onDelete={removePost} editing={editing} setEditing={setEditing} canManage={selected.authorId === session.uid} />}</section>;
}

function AdminDashboard({ session, posts, onRefresh }: { session: CommunitySession; posts: CommunityPost[]; onRefresh: () => Promise<void> }) {
  const [speciesId, setSpeciesId] = useState(baseSpecies[0]?.id ?? ""), [description, setDescription] = useState(baseSpecies[0]?.appearanceTraits ?? ""), [selected, setSelected] = useState<CommunityPost | null>(null), [editing, setEditing] = useState(false), [comments, setComments] = useState<CommunityComment[]>([]), [comment, setComment] = useState(""), [notice, setNotice] = useState("");
  const species = baseSpecies.find(item => item.id === speciesId);
  const selectSpecies = (id: string) => { const next = baseSpecies.find(item => item.id === id); setSpeciesId(id); setDescription(next?.appearanceTraits ?? ""); };
  const saveDescription = async () => { if (!species || !description.trim()) return; await saveCatalogOverride(session, { speciesId: species.id, description: description.trim(), updatedAt: new Date().toISOString() }); setNotice(`${species.koreanName} 설명을 저장했습니다.`); };
  const savePost = async () => { if (!selected) return; await updateCommunityPost(session, selected); setEditing(false); await onRefresh(); };
  const deletePost = async () => { if (!selected || !confirm("이 게시글을 삭제할까요?")) return; await deleteCommunityPost(session, selected.id); setSelected(null); await onRefresh(); };
  const addComment = async (event: FormEvent) => { event.preventDefault(); if (!selected || !comment.trim()) return; await createCommunityComment(session, selected.id, { authorId: session.uid, authorName: "관리자", authorAvatar: "🐚", body: comment.trim(), createdAt: new Date().toISOString() }); setComment(""); setComments(await listCommunityComments(session, selected.id)); };
  return <section className="screen community admin-dashboard"><p className="eyebrow">ADMINISTRATOR</p><h1>관리자 센터</h1><p className="safety">nowimminjun@gmail.com 계정으로 관리 중입니다.</p><section className="card"><h2>도감 설명 관리</h2><label>생물 선택<select value={speciesId} onChange={e => selectSpecies(e.target.value)}>{baseSpecies.map(item => <option value={item.id} key={item.id}>{item.group} · {item.koreanName}</option>)}</select></label><label>특징 설명<textarea value={description} onChange={e => setDescription(e.target.value)} /></label><button className="primary" onClick={saveDescription}>도감 설명 저장</button>{notice && <p className="muted">{notice}</p>}</section><div className="section-heading"><h2>커뮤니티 글 관리</h2><button onClick={onRefresh}>새로고침</button></div><div className="cards">{posts.map(post => <button className="community-post" key={post.id} onClick={() => { setSelected(post); setEditing(false); listCommunityComments(session, post.id).then(setComments); }}><span>{post.authorAvatar} {post.authorName}</span><b>{post.title}</b><small>{post.body}</small></button>)}</div>{selected && <PostModal post={selected} setPost={setSelected} comments={comments} comment={comment} setComment={setComment} onComment={addComment} onEdit={savePost} onDelete={deletePost} editing={editing} setEditing={setEditing} canManage />}</section>;
}

function AdminModeration({ session }: { session: CommunitySession }) { const [members, setMembers] = useState<{ uid: string; nickname: string; avatar: string; email: string }[]>([]), [posts, setPosts] = useState<CommunityPost[]>([]), [post, setPost] = useState<CommunityPost | null>(null), [comments, setComments] = useState<CommunityComment[]>([]), [notice, setNotice] = useState(""); const load = async () => { setMembers(await listCommunityMembers(session)); setPosts(await listCommunityPosts(session)); }; useEffect(() => { load(); }, []); const open = async (item: CommunityPost) => { setPost(item); setComments(await listCommunityComments(session, item.id)); }; return <section className="screen community admin-moderation"><section className="card"><h2>회원 관리</h2><p className="muted">추방된 회원은 커뮤니티 글과 댓글을 작성·수정할 수 없습니다.</p>{members.map(member => <div className="community-comment" key={member.uid}><b>{member.avatar} {member.nickname || member.email}</b><small>{member.email}</small>{member.email !== adminEmail && <button className="danger" onClick={async () => { if (!confirm(`${member.email} 회원을 추방할까요?`)) return; await banCommunityMember(session, member); setNotice("회원 추방을 적용했습니다."); }}>회원 추방</button>}</div>)}{notice && <p className="error">{notice}</p>}</section><section className="card"><h2>댓글 관리</h2>{posts.map(item => <button className="community-post" onClick={() => open(item)} key={item.id}><b>{item.title}</b><small>{item.authorName}</small></button>)}{post && <div className="admin-comment-list"><h3>{post.title}</h3>{comments.map(comment => <div className="community-comment" key={comment.id}><b>{comment.authorAvatar} {comment.authorName}</b><p>{comment.body}</p><button className="danger" onClick={async () => { if (!confirm("이 댓글을 삭제할까요?")) return; await deleteCommunityComment(session, post.id, comment.id); setComments(await listCommunityComments(session, post.id)); }}>댓글 삭제</button></div>)}</div>}</section></section>; }
function PostModal({ post, setPost, comments, comment, setComment, onComment, onEdit, onDelete, editing, setEditing, canManage }: { post: CommunityPost; setPost: (post: CommunityPost | null) => void; comments: CommunityComment[]; comment: string; setComment: (value: string) => void; onComment: (event: FormEvent) => void; onEdit: () => void; onDelete: () => void; editing: boolean; setEditing: (value: boolean) => void; canManage: boolean }) { return <div className="community-modal" role="dialog" onClick={() => setPost(null)}><article className="card" onClick={event => event.stopPropagation()}><button className="back" onClick={() => setPost(null)}>← 목록으로</button>{editing ? <><label>제목<input value={post.title} onChange={e => setPost({ ...post, title: e.target.value })} /></label><label>내용<textarea value={post.body} onChange={e => setPost({ ...post, body: e.target.value })} /></label><button className="primary" onClick={onEdit}>수정 저장</button></> : <><p>{post.authorAvatar} {post.authorName}</p><h2>{post.title}</h2>{post.photo && <img className="community-full-image" src={post.photo} alt="게시글 사진" />}<p>{post.body}</p>{canManage && <div className="inline-actions"><button onClick={() => setEditing(true)}>글 수정</button><button className="danger" onClick={onDelete}>글 삭제</button></div>}</>}<h2>댓글</h2>{comments.map(item => <div className="community-comment" key={item.id}><b>{item.authorAvatar} {item.authorName}</b><p>{item.body}</p></div>)}<form onSubmit={onComment}><label>댓글<input value={comment} onChange={e => setComment(e.target.value)} /></label><button className="primary">댓글 등록</button></form></article></div>; }
