"use client";

import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { baseSpecies } from "@/src/data/baseSpecies";
import { appConfig } from "@/src/config/app";
import { MockSpeciesIdentifier } from "@/src/lib/identification/MockSpeciesIdentifier";
import { compressImage, imageWarnings } from "@/src/lib/image/quality";
import { authKey, deleteData, guestId, loadData, saveData } from "@/src/lib/storage/localStore";
import { cachePhoto } from "@/src/lib/storage/photoStore";
import { AppData, Category, IdentificationResult, Observation, UserProfile } from "@/src/types";

type View = "welcome" | "login" | "signup" | "home" | "atlas" | "capture" | "result" | "personal" | "unknown" | "records" | "profile" | "detail";
const identifier = new MockSpeciesIdentifier();
const notice = "생물을 만지거나 이동시키지 말고, 원래 서식 환경을 훼손하지 않은 상태에서 사진으로만 관찰해 주세요.";
const fmt = (date?: string) => date ? new Intl.DateTimeFormat("ko-KR", { month: "long", day: "numeric" }).format(new Date(date)) : "—";
const newId = () => crypto.randomUUID?.() ?? `${Date.now()}-${Math.random()}`;

export default function Home() {
  const [view, setView] = useState<View>("welcome");
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [data, setData] = useState<AppData | null>(null);
  const [photos, setPhotos] = useState<string[]>([]);
  const [files, setFiles] = useState<File[]>([]);
  const [result, setResult] = useState<IdentificationResult | null>(null);
  const [selectedSpecies, setSelectedSpecies] = useState<string | null>(null);
  const [toast, setToast] = useState("");
  const [demoMode, setDemoMode] = useState<"base" | "external" | "unidentified">("base");
  const [filter, setFilter] = useState("전체");
  const [query, setQuery] = useState("");
  const [darkMode, setDarkMode] = useState(false);
  const [form, setForm] = useState({ location: "부산 갯벌 탐방 구역", habitat: "펄과 모래가 섞인 갯벌", notes: "", temporaryName: "", mergeId: "" });

  useEffect(() => { const raw = localStorage.getItem(authKey); if (raw) { const saved = JSON.parse(raw) as UserProfile; if (!saved.isGuest) { setProfile(saved); setData(loadData(saved)); setView("home"); } } }, []);
  useEffect(() => { if (data) saveData(data); }, [data]);
  useEffect(() => { setDarkMode(localStorage.getItem("mudflat-log:theme") === "dark"); }, []);
  useEffect(() => { document.documentElement.dataset.theme = darkMode ? "dark" : "light"; localStorage.setItem("mudflat-log:theme", darkMode ? "dark" : "light"); }, [darkMode]);
  const summary = useMemo(() => {
    const atlas = data?.atlas ?? [], obs = data?.observations ?? [];
    const discovered = atlas.filter(item => item.discovered).length;
    const personal = obs.filter(item => item.category === "PERSONAL");
    return { discovered, personalCount: new Set(personal.map(item => item.speciesId ?? item.temporaryName)).size, unknown: obs.filter(item => item.category === "UNIDENTIFIED").length, observations: obs.length, percent: Math.round(discovered / baseSpecies.length * 100) };
  }, [data]);
  const enter = (next: UserProfile) => { localStorage.setItem(authKey, JSON.stringify(next)); setProfile(next); setData(loadData(next)); setView("home"); };
  const guest = () => enter({ id: guestId, nickname: "체험 탐방자", isGuest: true, joinedAt: new Date().toISOString() });
  const update = (mutate: (current: AppData) => AppData) => setData(current => current ? mutate(current) : current);
  const clearCapture = () => { setPhotos([]); setFiles([]); setResult(null); setSelectedSpecies(null); setForm({ location: "부산 갯벌 탐방 구역", habitat: "펄과 모래가 섞인 갯벌", notes: "", temporaryName: "", mergeId: "" }); };
  const receivePhotos = async (event: ChangeEvent<HTMLInputElement>) => { const chosen = Array.from(event.target.files ?? []).slice(0, 3); setFiles(chosen); const compressed = await Promise.all(chosen.map(compressImage)); await Promise.allSettled(compressed.map((photo, index) => cachePhoto(`${profile.id}-${Date.now()}-${index}`, photo))); setPhotos(compressed); };
  const analyze = async () => { if (!photos.length) return setToast("사진을 한 장 이상 등록해 주세요."); setResult(await identifier.identify(photos, demoMode)); setView("result"); };
  const saveObservation = (category: Category, speciesId?: string) => {
    if (!data || !profile) return; const now = new Date().toISOString(); const existing = category === "BASE" ? data.atlas.find(item => item.speciesId === speciesId) : undefined;
    const observation: Observation = { id: newId(), userId: profile.id, speciesId, temporaryName: category === "PERSONAL" ? (form.temporaryName || `${result?.detectedGroup ?? "이름을 확인 중인"} 생물`) : undefined, category, photos, observedAt: now, approximateLocation: form.location || "위치 저장 안 함", habitatType: form.habitat, notes: form.notes, identificationStatus: category === "UNIDENTIFIED" ? "UNIDENTIFIED" : category === "BASE" ? "CONFIRMED" : "REVIEWING", identificationSource: "데모 판별 및 사용자 확인", createdAt: now, updatedAt: now, detectedGroup: result?.detectedGroup, reason: result?.reason };
    update(current => ({ ...current, observations: [observation, ...current.observations], atlas: category === "BASE" ? existing ? current.atlas.map(item => item.speciesId === speciesId ? { ...item, representativePhoto: item.representativePhoto ?? photos[0], lastObservedAt: now, observationCount: item.observationCount + 1 } : item) : [...current.atlas, { userId: profile.id, speciesId: speciesId!, discovered: true, representativePhoto: photos[0], firstObservedAt: now, lastObservedAt: now, observationCount: 1 }] : current.atlas }));
    setToast(category === "BASE" && !existing ? "기본 도감의 새로운 생물을 발견했어요!" : category === "UNIDENTIFIED" ? "미확인 생물함에 안전하게 저장했어요." : "나의 발견 도감에 기록했어요."); clearCapture(); setView(category === "UNIDENTIFIED" ? "unknown" : category === "PERSONAL" ? "personal" : "atlas");
  };
  const nav = (next: View) => { clearCapture(); setView(next); };
  if (!profile || !data) return <AuthScreen view={view} setView={setView} guest={guest} enter={enter} />;
  const species = selectedSpecies ? baseSpecies.find(item => item.id === selectedSpecies) : undefined;
  return <main className="app-shell">
    {toast && <div className="toast" role="status">✓ {toast}<button onClick={() => setToast("")} aria-label="알림 닫기">×</button></div>}
    <header className="app-header"><button className="brand" onClick={() => nav("home")}><span>◒</span>{appConfig.name}</button><button className="region" onClick={() => setToast("위치는 넓은 지역명으로만 저장됩니다.")}>⌖ {appConfig.defaultRegion}</button>{profile.isGuest && <span className="account-actions"><button onClick={() => { localStorage.removeItem(authKey); setProfile(null); setData(null); setView("login"); }}>로그인</button><button onClick={() => { localStorage.removeItem(authKey); setProfile(null); setData(null); setView("signup"); }}>회원가입</button></span>}<button className="icon-button theme-toggle" onClick={() => setDarkMode(value => !value)} aria-label={darkMode ? "라이트 모드로 전환" : "다크 모드로 전환"} aria-pressed={darkMode}>{darkMode ? "☀" : "☾"}</button><button className="icon-button" onClick={() => setToast(notice)} aria-label="관찰 도움말">?</button></header>
    {profile.isGuest && <div className="guest-banner">현재 체험 모드입니다. 계정을 만들면 도감과 관찰 기록을 안전하게 보관하고 다른 기기에서도 확인할 수 있습니다.</div>}
    {view === "home" && <Dashboard summary={summary} data={data} onNavigate={nav} onSelect={(id) => { setSelectedSpecies(id); setView("detail"); }} />}
    {view === "atlas" && <Atlas data={data} filter={filter} setFilter={setFilter} query={query} setQuery={setQuery} onSelect={(id) => { setSelectedSpecies(id); setView("detail"); }} />}
    {view === "detail" && species && <SpeciesDetail species={species} data={data} onBack={() => nav("atlas")} onCapture={() => { setSelectedSpecies(species.id); setView("capture"); }} onRepresentative={(photo) => update(current => ({ ...current, atlas: current.atlas.map(entry => entry.speciesId === species.id ? { ...entry, representativePhoto: photo } : entry) }))} />}
    {view === "capture" && <Capture photos={photos} files={files} receive={receivePhotos} analyze={analyze} setMode={setDemoMode} mode={demoMode} onCancel={() => nav("home")} />}
    {view === "result" && result && <ResultScreen result={result} selected={selectedSpecies} setSelected={setSelectedSpecies} setForm={setForm} form={form} onSave={saveObservation} />}
    {view === "personal" && <Personal data={data} onNavigate={nav} />}
    {view === "unknown" && <Unknown data={data} onMove={(obs) => { update(current => ({ ...current, observations: current.observations.map(item => item.id === obs.id ? { ...item, category: "PERSONAL", temporaryName: item.temporaryName || `${item.detectedGroup ?? "이름을 확인 중인"} 생물`, identificationStatus: "REVIEWING" } : item) })); setToast("나의 발견 도감으로 옮겼어요."); }} onDelete={(id) => update(current => ({ ...current, observations: current.observations.filter(item => item.id !== id) }))} />}
    {view === "records" && <Records data={data} onDelete={(id) => update(current => ({ ...current, observations: current.observations.filter(item => item.id !== id) }))} />}
    {view === "profile" && <Profile profile={profile} summary={summary} onUpdate={(nickname) => { const next = { ...profile, nickname }; setProfile(next); localStorage.setItem(authKey, JSON.stringify(next)); update(current => ({ ...current, profile: next })); setToast("프로필을 저장했어요."); }} onExport={() => { const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "mudflat-log-export.json"; link.click(); URL.revokeObjectURL(url); }} onReset={() => { if (confirm("현재 계정의 도감과 기록을 초기화할까요?")) { deleteData(profile.id); setData(loadData(profile)); setToast("데이터를 초기화했어요."); } }} onLogout={() => { localStorage.removeItem(authKey); setProfile(null); setData(null); setView("welcome"); }} />}
    <BottomNav view={view} navigate={nav} />
  </main>;
}

function AuthScreen({ view, setView, guest, enter }: { view: View; setView: (v: View) => void; guest: () => void; enter: (p: UserProfile) => void }) {
 const [email, setEmail] = useState("demo@mudflat.app"), [password, setPassword] = useState("demo1234"), [nickname, setNickname] = useState(""), [agreed, setAgreed] = useState(false), [error, setError] = useState("");
 const login = () => { if (email !== "demo@mudflat.app" || password !== "demo1234") return setError("이메일 또는 비밀번호를 확인해 주세요."); enter({ id: "demo-user", nickname: "데모 탐방자", email, isGuest: false, joinedAt: new Date().toISOString() }); };
 const signup = () => { if (nickname.trim().length < 2) return setError("닉네임은 2자 이상 입력해 주세요."); if (/[가-힣ㄱ-ㅎㅏ-ㅣ]/.test(email)) return setError("아이디는 한글 없이 영문, 숫자, 기호로만 입력해 주세요."); if (!/^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/.test(email)) return setError("아이디는 영문 이메일 형식으로 입력해 주세요."); if (password.length < 8) return setError("비밀번호는 8자 이상이어야 합니다."); if (!agreed) return setError("이용약관과 개인정보 처리 안내에 동의해 주세요."); enter({ id: `user-${email}`, nickname, email, isGuest: false, joinedAt: new Date().toISOString() }); };
 if (view === "welcome") return <main className="welcome"><div className="welcome-art">◒</div><p className="eyebrow">BUSAN MUDFLAT FIELD NOTE</p><h1>{appConfig.name}</h1><p>{appConfig.tagline}</p><div className="card principle">사진으로만 관찰하고, 생물의 집은 그대로 남겨 주세요.</div><button className="primary" onClick={() => setView("login")}>로그인</button><button className="secondary" onClick={() => setView("signup")}>회원가입</button><button className="text-button" onClick={guest}>회원가입 없이 체험하기 →</button></main>;
 return <main className="auth"><button className="back" onClick={() => setView("welcome")}>← 돌아가기</button><p className="eyebrow">{view === "login" ? "데모 로그인" : "새 탐방자 등록"}</p><h1>{view === "login" ? "다시 만나서 반가워요" : "나만의 도감을 시작해요"}</h1>{view === "signup" && <label>닉네임<input value={nickname} onChange={e => setNickname(e.target.value)} placeholder="2자 이상" /></label>}<label>{view === "signup" ? "아이디 (영문 이메일)" : "이메일"}<input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder={view === "signup" ? "example@email.com" : undefined} /></label>{view === "signup" && <p className="field-hint">아이디는 한글 없이 영문, 숫자, 기호만 사용할 수 있습니다.</p>}<label>비밀번호<input type="password" value={password} onChange={e => setPassword(e.target.value)} /></label>{view === "signup" && <label className="terms"><input type="checkbox" checked={agreed} onChange={e => setAgreed(e.target.checked)} /> <span>이용약관과 개인정보 처리 안내에 동의합니다. <b>(필수)</b><br />위치정보는 넓은 지역명으로만 저장됩니다.</span></label>}{error && <p className="error">{error}</p>}<button className="primary" onClick={view === "login" ? login : signup}>{view === "login" ? "로그인" : "회원가입"}</button>{view === "login" && <><button className="secondary" onClick={guest}>체험 계정으로 로그인</button><button className="text-button" onClick={() => setView("signup")}>회원가입으로 이동</button></>}</main>;
}

function Dashboard({ summary, data, onNavigate, onSelect }: { summary: { discovered: number; personalCount: number; unknown: number; observations: number; percent: number }; data: AppData; onNavigate: (v: View) => void; onSelect: (id: string) => void }) {
 const missing = baseSpecies.filter(species => !data.atlas.some(entry => entry.speciesId === species.id)).slice(0, 3); const recent = data.observations.slice(0, 2);
 return <section className="screen"><div className="hero"><p className="eyebrow">오늘의 탐방</p><h1>기록할수록 넓어지는<br /><em>나만의 바다 도감</em></h1><button className="capture-cta" onClick={() => onNavigate("capture")}>◉ 생물 촬영하기 <span>→</span></button></div><div className="stats"><Stat value={`${summary.discovered} / ${baseSpecies.length}`} label="기본 도감" /><Stat value={`${summary.personalCount}종`} label="나의 추가 발견" /><Stat value={`${summary.unknown}건`} label="미확인 생물" /><Stat value={`${summary.observations}회`} label="총 관찰 기록" /></div><section className="progress card"><div><p className="eyebrow">관찰 진행률</p><strong>기본 도감 {summary.percent}%</strong></div><div className="progress-track"><i style={{ width: `${summary.percent}%` }} /></div><span>{summary.discovered}종 발견 · 총 {summary.discovered + summary.personalCount}종 기록</span></section><section><h2>오늘의 관찰 수칙</h2><p className="safety">✦ {notice}</p></section><section><div className="section-heading"><h2>아직 만나지 못한 생물</h2><button onClick={() => onNavigate("atlas")}>전체 보기</button></div><div className="mini-list">{missing.map(species => <button className="mini-card" onClick={() => onSelect(species.id)} key={species.id}><span className="silhouette">◌</span><span><b>{species.koreanName}</b><small>{species.habitat}</small></span><span>→</span></button>)}</div></section>{recent.length > 0 && <section><h2>최근 발견</h2>{recent.map(item => <div className="record-row" key={item.id}>{item.photos[0] ? <img src={item.photos[0]} alt="관찰 사진" /> : <span className="silhouette">◌</span>}<span><b>{item.temporaryName || baseSpecies.find(s => s.id === item.speciesId)?.koreanName || "미확인 생물"}</b><small>{fmt(item.observedAt)} · {item.approximateLocation}</small></span></div>)}</section>}<section><h2>주변에서 찾아볼 수 있는 환경</h2><div className="habitats"><span>펄갯벌</span><span>갯골 주변</span><span>바위 주변</span><span>물웅덩이</span></div><p className="muted">이 구역에서 관찰될 가능성이 있습니다. 정확한 출현 여부는 물때와 계절에 따라 달라질 수 있습니다.</p></section></section>;
}
function Stat({ value, label }: { value: string; label: string }) { return <div className="stat"><b>{value}</b><span>{label}</span></div>; }
function Atlas({ data, filter, setFilter, query, setQuery, onSelect }: { data: AppData; filter: string; setFilter: (v: string) => void; query: string; setQuery: (v: string) => void; onSelect: (id: string) => void }) { const items = baseSpecies.filter(species => { const discovered = data.atlas.some(entry => entry.speciesId === species.id); return (!query || species.koreanName.includes(query) || species.group.includes(query)) && (filter === "전체" || filter === "발견 완료" && discovered || filter === "미발견" && !discovered); }); return <section className="screen"><p className="eyebrow">기본 도감 {baseSpecies.length}종</p><h1>공통으로 시작하는<br />갯벌 친구들</h1><input className="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="생물 이름 또는 생물군 검색" /><div className="chips">{["전체", "발견 완료", "미발견"].map(item => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="species-grid">{items.map(species => { const entry = data.atlas.find(item => item.speciesId === species.id); return <button className="species-card" key={species.id} onClick={() => onSelect(species.id)}>{entry?.representativePhoto ? <img src={entry.representativePhoto} alt={`${species.koreanName} 대표 사진`} /> : <div className="silhouette large">◌</div>}<span className={`status ${entry ? "done" : "locked"}`}>{entry ? "✓ 발견 완료" : "◌ 아직 발견하지 못했어요"}</span><b>{species.koreanName}</b><small>{species.group} · {species.discoveryDifficulty}</small></button>; })}</div></section>; }
function SpeciesDetail({ species, data, onBack, onCapture, onRepresentative }: { species: typeof baseSpecies[number]; data: AppData; onBack: () => void; onCapture: () => void; onRepresentative: (photo: string) => void }) { const entry = data.atlas.find(item => item.speciesId === species.id); const observations = data.observations.filter(item => item.speciesId === species.id); return <section className="screen detail"><button className="back" onClick={onBack}>← 도감으로</button><div className="detail-image">{entry?.representativePhoto ? <img src={entry.representativePhoto} alt={`${species.koreanName} 대표 사진`} /> : <span className="silhouette large">◌</span>}</div><span className="badge">{species.group} · {species.discoveryDifficulty}</span><h1>{species.koreanName}</h1><i>{species.scientificName}</i>{entry && <div className="facts"><span>첫 발견 <b>{fmt(entry.firstObservedAt)}</b></span><span>관찰 기록 <b>{entry.observationCount}회</b></span></div>}<button className="primary" onClick={onCapture}>◉ 이 생물 촬영하기</button><p className="safety">✦ {notice}</p><details open><summary>관찰 안내</summary><p>{species.observationTips}</p><p><b>관찰 환경:</b> {species.habitat} · {species.bestObservationTime}</p><p><b>외형 특징:</b> {species.appearanceTraits}</p></details><details><summary>서식 환경과 역할</summary><p>{species.ecologicalRole}</p><p>{species.broadObservationAreas.join(" · ")}에서 관찰될 가능성이 있습니다.</p></details>{observations.length > 0 && <section><h2>내 사진첩</h2><div className="photo-strip">{observations.flatMap(item => item.photos).map((photo, index) => <button key={`${photo.slice(-16)}-${index}`} onClick={() => onRepresentative(photo)}><img src={photo} alt={`${species.koreanName} 추가 사진`} /></button>)}</div></section>}</section>; }
function Capture({ photos, files, receive, analyze, setMode, mode, onCancel }: { photos: string[]; files: File[]; receive: (e: ChangeEvent<HTMLInputElement>) => void; analyze: () => void; setMode: (m: "base" | "external" | "unidentified") => void; mode: "base" | "external" | "unidentified"; onCancel: () => void }) { const warnings = imageWarnings(files); return <section className="screen"><button className="back" onClick={onCancel}>← 돌아가기</button><p className="eyebrow">사진으로 안전하게 관찰하기</p><h1>생물의 모습을<br />기록해 주세요</h1><p className="safety">✦ {notice}</p><div className="capture-box"><input id="photo" type="file" accept="image/*" capture="environment" multiple onChange={receive} /><label htmlFor="photo">◉<b>사진 촬영 또는 선택</b><small>최대 3장 · 카메라와 갤러리 모두 가능</small></label></div>{photos.length > 0 && <div className="photo-preview">{photos.map((photo, index) => <img key={photo.slice(-16)} src={photo} alt={`선택한 사진 ${index + 1}`} />)}</div>}{warnings.length > 0 && <div className="warning">⚠ {warnings.map(item => <p key={item}>{item}</p>)}</div>}<div className="demo-panel"><b>데모 판별 모드</b><p>실제 AI 연결 전 흐름 검증용입니다.</p><div className="chips">{(["base", "external", "unidentified"] as const).map(item => <button className={mode === item ? "active" : ""} onClick={() => setMode(item)} key={item}>{item === "base" ? "기본 도감 생물" : item === "external" ? "도감 밖 생물" : "미확인 생물"}</button>)}</div></div><button className="primary" disabled={!photos.length} onClick={analyze}>사진 분석 결과 보기 →</button></section>; }

function ResultScreen({ result, selected, setSelected, form, setForm, onSave }: { result: IdentificationResult; selected: string | null; setSelected: (id: string) => void; form: { location: string; habitat: string; notes: string; temporaryName: string; mergeId: string }; setForm: (v: typeof form) => void; onSave: (category: Category, speciesId?: string) => void }) {
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const assign = (key: keyof typeof form, value: string) => setForm({ ...form, [key]: value });
  if (result.resultType === "UNIDENTIFIED") return <section className="screen"><p className="eyebrow">IDENTIFICATION RESULT</p><h1>More photos<br />are needed</h1><p className="result-reason">{result.reason}</p><FormFields form={form} assign={assign} /><button className="primary" onClick={() => onSave("UNIDENTIFIED")}>Save as unidentified</button></section>;
  if (result.resultType === "EXTERNAL_SPECIES") return <section className="screen"><p className="eyebrow">IDENTIFICATION RESULT</p><h1>{result.detectedGroup}<br />is suggested</h1><p className="result-reason">{result.reason}</p><FormFields form={form} assign={assign} personal /><button className="primary" onClick={() => onSave("PERSONAL")}>Add to my discoveries</button></section>;
  return <section className="screen"><p className="eyebrow">IDENTIFICATION RESULT</p><h1>{result.detectedGroup}<br />is suggested</h1><p className="result-reason">{result.reason}</p><h2>Check the visible traits</h2>{result.suggestedQuestions.map(question => <div className="question" key={question.id}><b>{question.question}</b><div className="chips">{["Yes", "No", "Not sure", "Not visible"].map(answer => <button className={answers[question.id] === answer ? "active" : ""} key={answer} onClick={() => setAnswers({ ...answers, [question.id]: answer })}>{answer}</button>)}</div></div>)}<h2>Suggested candidates</h2>{result.candidates.map(candidate => <button className={`candidate ${selected === candidate.speciesId ? "selected" : ""}`} key={candidate.name} onClick={() => candidate.speciesId && setSelected(candidate.speciesId)}><span><b>{candidate.name}</b><small>{candidate.traits.join(" / ")}</small></span><em>{candidate.confidenceLevel}</em></button>)}<FormFields form={form} assign={assign} /><p className="muted">Confirm after comparing the candidate and visible traits. This is an estimate, not a final identification.</p><button className="primary" disabled={!selected} onClick={() => onSave("BASE", selected ?? undefined)}>Register selected species</button></section>;
}
function FormFields({ form, assign, personal = false }: { form: { location: string; habitat: string; notes: string; temporaryName: string }; assign: (k: "location" | "habitat" | "notes" | "temporaryName", v: string) => void; personal?: boolean }) { return <div className="observation-form">{personal && <label>이름 또는 임시 이름<input value={form.temporaryName} onChange={e => assign("temporaryName", e.target.value)} placeholder="예: 고둥류 미확인 종" /></label>}<label>대략적인 발견 지역<input value={form.location} onChange={e => assign("location", e.target.value)} /></label><label>서식 환경<select value={form.habitat} onChange={e => assign("habitat", e.target.value)}><option>펄과 모래가 섞인 갯벌</option><option>펄갯벌</option><option>바위 주변</option><option>물웅덩이 주변</option></select></label><label>관찰 메모<textarea value={form.notes} onChange={e => assign("notes", e.target.value)} placeholder="크기, 움직임, 날씨 등을 남겨 보세요." /></label></div>; }
function Personal({ data, onNavigate }: { data: AppData; onNavigate: (v: View) => void }) { const items = data.observations.filter(item => item.category === "PERSONAL"); return <section className="screen"><p className="eyebrow">나의 발견 도감</p><h1>기본 도감 밖에서<br />만난 생물들</h1><div className="stats"><Stat value={`${new Set(items.map(item => item.temporaryName)).size}종`} label="추가 발견" /><Stat value={`${items.length}회`} label="추가 관찰" /><Stat value={`${items.filter(item => item.identificationStatus === "CONFIRMED").length}종`} label="확인 완료" /></div>{items.length ? <div className="cards">{items.map(item => <ObservationCard item={item} key={item.id} />)}</div> : <Empty text="아직 기본 도감 밖의 생물을 발견하지 못했어요. 갯벌을 탐험하며 나만의 발견을 기록해 보세요." action={() => onNavigate("capture")} />}</section>; }
function Unknown({ data, onMove, onDelete }: { data: AppData; onMove: (o: Observation) => void; onDelete: (id: string) => void }) { const items = data.observations.filter(item => item.category === "UNIDENTIFIED"); return <section className="screen"><p className="eyebrow">미확인 생물함</p><h1>나중에 다시<br />비교해 볼 기록</h1><p className="muted">판별이 어려운 사진도 버리지 않고 안전하게 보관합니다.</p>{items.length ? <div className="cards">{items.map(item => <div className="observation-card" key={item.id}><ObservationCard item={item} /><div className="inline-actions"><button onClick={() => onMove(item)}>나의 도감으로 이동</button><button className="danger" onClick={() => onDelete(item.id)}>기록 삭제</button></div></div>)}</div> : <Empty text="아직 미확인 생물 기록이 없어요." />}</section>; }
function Records({ data, onDelete }: { data: AppData; onDelete: (id: string) => void }) { return <section className="screen"><p className="eyebrow">전체 관찰 기록</p><h1>시간순으로 보는<br />나의 탐방 노트</h1>{data.observations.length ? <div className="cards">{data.observations.map(item => <div className="observation-card" key={item.id}><ObservationCard item={item} /><button className="danger" onClick={() => onDelete(item.id)}>기록 삭제</button></div>)}</div> : <Empty text="아직 관찰 기록이 없어요. 첫 생물을 사진으로 기록해 보세요." />}</section>; }
function ObservationCard({ item }: { item: Observation }) { return <article className="record-card">{item.photos[0] ? <img src={item.photos[0]} alt="관찰 사진" /> : <span className="silhouette">◌</span>}<div><span className="badge">{item.category === "BASE" ? "기본 도감" : item.category === "PERSONAL" ? "나의 도감" : "미확인"}</span><h3>{item.temporaryName || baseSpecies.find(s => s.id === item.speciesId)?.koreanName || item.detectedGroup || "미확인 생물"}</h3><p>{fmt(item.observedAt)} · {item.approximateLocation}</p><small>{item.notes || item.reason || "관찰 메모 없음"}</small></div></article>; }
function Empty({ text, action }: { text: string; action?: () => void }) { return <div className="empty"><span>◌</span><p>{text}</p>{action && <button className="secondary" onClick={action}>생물 촬영하기</button>}</div>; }
function Profile({ profile, summary, onUpdate, onExport, onReset, onLogout }: { profile: UserProfile; summary: { discovered: number; personalCount: number; unknown: number; observations: number }; onUpdate: (name: string) => void; onExport: () => void; onReset: () => void; onLogout: () => void }) { const [name, setName] = useState(profile.nickname); return <section className="screen"><p className="eyebrow">프로필과 설정</p><h1>나의 탐방 정보</h1><div className="profile-head"><span>◒</span><div><b>{profile.nickname}</b><small>{profile.isGuest ? "현재 체험 모드" : profile.email}</small></div></div><div className="stats"><Stat value={`${summary.discovered}/${baseSpecies.length}`} label="기본 도감" /><Stat value={`${summary.personalCount}종`} label="추가 발견" /><Stat value={`${summary.observations}회`} label="관찰 기록" /><Stat value={`${summary.unknown}건`} label="미확인" /></div><div className="settings"><h2>계정 설정</h2><label>닉네임<input value={name} onChange={e => setName(e.target.value)} /></label><button className="secondary" onClick={() => onUpdate(name)}>닉네임 저장</button><button className="secondary" onClick={onExport}>기록 내보내기</button><button className="secondary" onClick={onReset}>현재 데이터 초기화</button><button className="danger full" onClick={onLogout}>로그아웃</button></div><p className="muted">공개 범위는 기본적으로 비공개입니다. 민감한 생물의 정확한 위치는 공개하지 않습니다.</p></section>; }
function BottomNav({ view, navigate }: { view: View; navigate: (v: View) => void }) { const nav = [["home", "⌂", "홈"], ["atlas", "▦", "기본 도감"], ["capture", "◉", "촬영"], ["personal", "♧", "나의 도감"], ["records", "☷", "기록"]] as const; return <><nav className="bottom-nav">{nav.map(([id, icon, label]) => <button key={id} className={view === id ? "active" : ""} onClick={() => navigate(id)}><span>{icon}</span>{label}</button>)}</nav><button className="profile-fab" onClick={() => navigate("profile")} aria-label="프로필 및 설정">⚙</button></>; }
